---
title: "Classification"
author: "Bill Lang"
date: "3/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glmnet)
```



Decision tree

```{r}
data


n <- nrow(data)
test_idx <- sample.int(n, size = round(0.2*n))
train <- data[-test_idx,]


form <- as.formula("LeagueIndex ~ Age + HoursPerWeek + SelectByHotkeys + AssignToHotkeys + UniqueHotkeys + MinimapAttacks + NumberOfPACs + GapBetweenPACs + ActionLatency + ActionsInPAC + TotalMapExplored + WorkersMade + UniqueUnitsMade + ComplexUnitsMade")

tree <- rpart(form, data)

tree


plot(tree)

text(tree, use.n = TREU, all = TRUE, cex = .2)


plot(as.party(tree))
as.party(tree)
```



Classification (Middle Split)


```{r}
class <- data %>% 
  mutate(Leauge = ifelse((LeagueIndex >= 4), 1, 0))
class
```
```{r}

trainid <- sample(1:nrow(class), nrow(data)*0.8 , replace=F)
train <- class[trainid,]
test <- class[-trainid,]
dim(train); dim(test)

```


```{r}
logit <- glm(Leauge~ Age + HoursPerWeek + SelectByHotkeys + AssignToHotkeys + UniqueHotkeys + MinimapAttacks + NumberOfPACs + GapBetweenPACs + ActionLatency + ActionsInPAC + TotalMapExplored + WorkersMade + UniqueUnitsMade + ComplexUnitsMade, data = train, family = "binomial")

logitProb <- predict(logit, test, type = "response")

logitPred <- ifelse(logitProb > 0.5, 1, 0)

table(logitPred, test$Leauge)

mean(logitPred != test$Leauge)

```

KNN

```{r}



```

This is just to see if the push works correctly. It does! asf 
