---
title: "Dataset Cleaning"
author: "Bill Lang"
date: "3/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

```{r}

urlfile = "https://raw.githubusercontent.com/bill-spec/Starcarft-2---Leauge-Predictor/master/Leauge.csv"

league <- read.csv(url(urlfile))

save(league, file = "league.RData")

load("league.RData")

```

```{r}
league <- league %>% 
  remove_rownames %>% 
  column_to_rownames(var="GameID")

league <- league %>% na.omit()
dim(league)
```






TotalHours and HoursPerWeek may be inproperly inputted. Many observations have times higher than possible. 

```{r}
league %>% group_by(HoursPerWeek) %>% summarise(number = n()) %>% arrange(desc(HoursPerWeek))
league %>% filter(HoursPerWeek > 56) %>% arrange(desc(HoursPerWeek))

#Any observations above 112 hours per week will be removed. This decision is arbitrary although should be consistent within the context of starcraft. 
#Players will play a lot, but it need not be above 112 hours. This is removing three observations. 

league <- league %>% filter(HoursPerWeek < 100) %>% arrange(desc(HoursPerWeek))
dim(league)
```

```{r}
league %>% group_by(TotalHours) %>% summarise(number = n()) %>% arrange(desc(TotalHours))
league %>% filter(TotalHours > 3000) %>% arrange(desc(TotalHours))

#Starcraft 2 had been out for over three years when this data was collected. The idea that a professional player would have half themax amount of hours (around 25,000/2) would be reasonable. Will be removing anyone with >9000 hours. THis is arbitrary. 

league <- league %>% filter(TotalHours < 9000) %>% arrange(desc(TotalHours))
dim(league)
```





These observations had been described as being repeated from idenitcal players and thus are being removed. 

```{r}

```





This should now be the final dataset. 

```{r}
dim(league)
league

summary(league)


```



